import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class FilmesService {

  listFilms:any[] = [
    {
      id:'LeComCre',
      images_1:[
        {url:'./assets/images/01_Lé com Cré/01_LCC_crop/LCC_FINAL_01459.png'},
        {url:'./assets/images/01_Lé com Cré/01_LCC_crop/LCC_FINAL_01461.png'},
        {url:'./assets/images/01_Lé com Cré/01_LCC_crop/LCC_FINAL_01463.png'},
        {url:'./assets/images/01_Lé com Cré/01_LCC_crop/LCC_FINAL_01465.png'},
        {url:'./assets/images/01_Lé com Cré/01_LCC_crop/LCC_FINAL_01467.png'},
        {url:'./assets/images/01_Lé com Cré/01_LCC_crop/LCC_FINAL_01469.png'},
        {url:'./assets/images/01_Lé com Cré/01_LCC_crop/LCC_FINAL_01471.png'},
        {url:'./assets/images/01_Lé com Cré/01_LCC_crop/LCC_FINAL_01473.png'},
        {url:'./assets/images/01_Lé com Cré/01_LCC_crop/LCC_FINAL_01475.png'},
        {url:'./assets/images/01_Lé com Cré/01_LCC_crop/LCC_FINAL_01477.png'},
        {url:'./assets/images/01_Lé com Cré/01_LCC_crop/LCC_FINAL_01479.png'},
        {url:'./assets/images/01_Lé com Cré/01_LCC_crop/LCC_FINAL_01485.png'}
      ],
      images_2:[
        {url:'./assets/images/01_Lé com Cré/02_LCC_crop/LCC_FINAL_01384.png'},
        {url:'./assets/images/01_Lé com Cré/02_LCC_crop/LCC_FINAL_01386.png'},
        {url:'./assets/images/01_Lé com Cré/02_LCC_crop/LCC_FINAL_01388.png'},
        {url:'./assets/images/01_Lé com Cré/02_LCC_crop/LCC_FINAL_01390.png'},
        {url:'./assets/images/01_Lé com Cré/02_LCC_crop/LCC_FINAL_01392.png'},
        {url:'./assets/images/01_Lé com Cré/02_LCC_crop/LCC_FINAL_01394.png'},
        {url:'./assets/images/01_Lé com Cré/02_LCC_crop/LCC_FINAL_01396.png'},
        {url:'./assets/images/01_Lé com Cré/02_LCC_crop/LCC_FINAL_01398.png'},
        {url:'./assets/images/01_Lé com Cré/02_LCC_crop/LCC_FINAL_01402.png'},
        {url:'./assets/images/01_Lé com Cré/02_LCC_crop/LCC_FINAL_01404.png'},
        {url:'./assets/images/01_Lé com Cré/02_LCC_crop/LCC_FINAL_01406.png'},
        {url:'./assets/images/01_Lé com Cré/02_LCC_crop/LCC_FINAL_01408.png'}
      ],
      images_3:[
        {url:'./assets/images/01_Lé com Cré/03_LCC_crop/LCC_FINAL_04414.png'},
        {url:'./assets/images/01_Lé com Cré/03_LCC_crop/LCC_FINAL_04416.png'},
        {url:'./assets/images/01_Lé com Cré/03_LCC_crop/LCC_FINAL_04418.png'},
        {url:'./assets/images/01_Lé com Cré/03_LCC_crop/LCC_FINAL_04420.png'},
        {url:'./assets/images/01_Lé com Cré/03_LCC_crop/LCC_FINAL_04422.png'},
        {url:'./assets/images/01_Lé com Cré/03_LCC_crop/LCC_FINAL_04424.png'},
        {url:'./assets/images/01_Lé com Cré/03_LCC_crop/LCC_FINAL_04425.png'},
        {url:'./assets/images/01_Lé com Cré/03_LCC_crop/LCC_FINAL_04427.png'},
        {url:'./assets/images/01_Lé com Cré/03_LCC_crop/LCC_FINAL_04428.png'},
        {url:'./assets/images/01_Lé com Cré/03_LCC_crop/LCC_FINAL_04430.png'},
        {url:'./assets/images/01_Lé com Cré/03_LCC_crop/LCC_FINAL_04431.png'},
        {url:'./assets/images/01_Lé com Cré/03_LCC_crop/LCC_FINAL_04433.png'}
      ],
      title:'LCC_TITLE',
      sub:'LCC_SUBTITLE',
      autor:'LCC_AUTOR',
      texto_1:'LCC_TEXTO_1',
      texto_2:'LCC_TEXTO_2',
      equipe:'LCC_EQUIPE_TITLE',
      equipe_txts:['LCC_EQUIPE_LINE_1','LCC_EQUIPE_LINE_2','LCC_EQUIPE_LINE_3','LCC_EQUIPE_LINE_4','LCC_EQUIPE_LINE_5','LCC_EQUIPE_LINE_6','LCC_EQUIPE_LINE_7','LCC_EQUIPE_LINE_8','LCC_EQUIPE_LINE_9','LCC_EQUIPE_LINE_10','LCC_EQUIPE_LINE_11'],
      elenco:'LCC_ELENCO',
      elenco_txts:['LCC_ELENCO_LINE_1','LCC_ELENCO_LINE_2','LCC_ELENCO_LINE_3','LCC_ELENCO_LINE_4','LCC_ELENCO_LINE_5','LCC_ELENCO_LINE_6','LCC_ELENCO_LINE_7'],
      premio:'LCC_PREMIACOES',
      premiacoes_txts:['LCC_PREMIACOES_LINE_1','LCC_PREMIACOES_LINE_2','LCC_PREMIACOES_LINE_3','LCC_PREMIACOES_LINE_4', 'LCC_PREMIACOES_LINE_5', 'LCC_PREMIACOES_LINE_6'],
      selecao_oficial:'LCC_SELECAO',
      selecao_oficial_txt:['LCC_SELECAO_LINE_1',
      'LCC_SELECAO_LINE_2',
      'LCC_SELECAO_LINE_3',
      'LCC_SELECAO_LINE_4',
      'LCC_SELECAO_LINE_5',
      'LCC_SELECAO_LINE_6',
      'LCC_SELECAO_LINE_7',
      'LCC_SELECAO_LINE_8',
      'LCC_SELECAO_LINE_9',
      'LCC_SELECAO_LINE_10',
      'LCC_SELECAO_LINE_11',
      'LCC_SELECAO_LINE_12',
      'LCC_SELECAO_LINE_13',
      'LCC_SELECAO_LINE_14',
      'LCC_SELECAO_LINE_15',
      'LCC_SELECAO_LINE_16',
      'LCC_SELECAO_LINE_17',
      'LCC_SELECAO_LINE_18',
      'LCC_SELECAO_LINE_19',
      'LCC_SELECAO_LINE_20',
      'LCC_SELECAO_LINE_21',
      'LCC_SELECAO_LINE_22',
      'LCC_SELECAO_LINE_23',
      'LCC_SELECAO_LINE_24',
      'LCC_SELECAO_LINE_25',
      'LCC_SELECAO_LINE_26',
      'LCC_SELECAO_LINE_27',
      'LCC_SELECAO_LINE_28',
      'LCC_SELECAO_LINE_29',
      'LCC_SELECAO_LINE_30',
      'LCC_SELECAO_LINE_31',
      'LCC_SELECAO_LINE_32']
    },
    {
      id:'Cefalopodes',
      images_1:[
        {url:'./assets/images/02_Cefalópodes/CEF_01_crop/CEF_AnimaticV2 (0-00-55-17).png'},
        {url:'./assets/images/02_Cefalópodes/CEF_01_crop/CEF_AnimaticV2 (0-00-56-05).png'},
        {url:'./assets/images/02_Cefalópodes/CEF_01_crop/CEF_AnimaticV2 (0-00-56-20).png'},
        {url:'./assets/images/02_Cefalópodes/CEF_01_crop/CEF_AnimaticV2 (0-00-57-16).png'},
        {url:'./assets/images/02_Cefalópodes/CEF_01_crop/CEF_AnimaticV2 (0-00-58-17).png'},
        {url:'./assets/images/02_Cefalópodes/CEF_01_crop/CEF_AnimaticV2 (0-00-59-01).png'},
        {url:'./assets/images/02_Cefalópodes/CEF_01_crop/CEF_AnimaticV2 (0-00-59-02).png'},
        {url:'./assets/images/02_Cefalópodes/CEF_01_crop/CEF_AnimaticV2 (0-00-59-14).png'},
        {url:'./assets/images/02_Cefalópodes/CEF_01_crop/CEF_AnimaticV2 (0-00-59-21).png'},
        {url:'./assets/images/02_Cefalópodes/CEF_01_crop/CEF_AnimaticV2 (0-01-00-06).png'},
        {url:'./assets/images/02_Cefalópodes/CEF_01_crop/CEF_AnimaticV2 (0-01-00-15).png'},
        {url:'./assets/images/02_Cefalópodes/CEF_01_crop/CEF_AnimaticV2 (0-01-00-23).png'}
      ],
      images_2:[
        {url:'./assets/images/01_Lé com Cré/02_LCC_crop/LCC_FINAL_01384.png'},
        {url:'./assets/images/01_Lé com Cré/02_LCC_crop/LCC_FINAL_01386.png'},
        {url:'./assets/images/01_Lé com Cré/02_LCC_crop/LCC_FINAL_01388.png'},
        {url:'./assets/images/01_Lé com Cré/02_LCC_crop/LCC_FINAL_01390.png'},
        {url:'./assets/images/01_Lé com Cré/02_LCC_crop/LCC_FINAL_01392.png'},
        {url:'./assets/images/01_Lé com Cré/02_LCC_crop/LCC_FINAL_01394.png'},
        {url:'./assets/images/01_Lé com Cré/02_LCC_crop/LCC_FINAL_01396.png'},
        {url:'./assets/images/01_Lé com Cré/02_LCC_crop/LCC_FINAL_01398.png'},
        {url:'./assets/images/01_Lé com Cré/02_LCC_crop/LCC_FINAL_01402.png'},
        {url:'./assets/images/01_Lé com Cré/02_LCC_crop/LCC_FINAL_01404.png'},
        {url:'./assets/images/01_Lé com Cré/02_LCC_crop/LCC_FINAL_01406.png'},
        {url:'./assets/images/01_Lé com Cré/02_LCC_crop/LCC_FINAL_01408.png'}
      ],
      images_3:[
        {url:'./assets/images/01_Lé com Cré/03_LCC_crop/LCC_FINAL_04414.png'},
        {url:'./assets/images/01_Lé com Cré/03_LCC_crop/LCC_FINAL_04416.png'},
        {url:'./assets/images/01_Lé com Cré/03_LCC_crop/LCC_FINAL_04418.png'},
        {url:'./assets/images/01_Lé com Cré/03_LCC_crop/LCC_FINAL_04420.png'},
        {url:'./assets/images/01_Lé com Cré/03_LCC_crop/LCC_FINAL_04422.png'},
        {url:'./assets/images/01_Lé com Cré/03_LCC_crop/LCC_FINAL_04424.png'},
        {url:'./assets/images/01_Lé com Cré/03_LCC_crop/LCC_FINAL_04425.png'},
        {url:'./assets/images/01_Lé com Cré/03_LCC_crop/LCC_FINAL_04427.png'},
        {url:'./assets/images/01_Lé com Cré/03_LCC_crop/LCC_FINAL_04428.png'},
        {url:'./assets/images/01_Lé com Cré/03_LCC_crop/LCC_FINAL_04430.png'},
        {url:'./assets/images/01_Lé com Cré/03_LCC_crop/LCC_FINAL_04431.png'},
        {url:'./assets/images/01_Lé com Cré/03_LCC_crop/LCC_FINAL_04433.png'}
      ],
      title:'CEF_TITLE',
      sub:'CEF_SUBTITLE',
      autor:'CEF_AUTOR',
      texto_1:'CEF_TEXTO_1',
      texto_2:'CEF_TEXTO_2',
      equipe:'CEF_EQUIPE'
    }
  ];
  constructor() { }
}
