import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class FilmesService {

  listFilms:any[] = [
    {
      id:'LeComCre',
      images_1:[
        {url:'./assets/images/01_Lé com Cré/01_LCC_crop/LCC_FINAL_01459.png'},
        {url:'./assets/images/01_Lé com Cré/01_LCC_crop/LCC_FINAL_01461.png'},
        {url:'./assets/images/01_Lé com Cré/01_LCC_crop/LCC_FINAL_01463.png'},
        {url:'./assets/images/01_Lé com Cré/01_LCC_crop/LCC_FINAL_01465.png'},
        {url:'./assets/images/01_Lé com Cré/01_LCC_crop/LCC_FINAL_01467.png'},
        {url:'./assets/images/01_Lé com Cré/01_LCC_crop/LCC_FINAL_01469.png'},
        {url:'./assets/images/01_Lé com Cré/01_LCC_crop/LCC_FINAL_01471.png'},
        {url:'./assets/images/01_Lé com Cré/01_LCC_crop/LCC_FINAL_01473.png'},
        {url:'./assets/images/01_Lé com Cré/01_LCC_crop/LCC_FINAL_01475.png'},
        {url:'./assets/images/01_Lé com Cré/01_LCC_crop/LCC_FINAL_01477.png'},
        {url:'./assets/images/01_Lé com Cré/01_LCC_crop/LCC_FINAL_01479.png'},
        {url:'./assets/images/01_Lé com Cré/01_LCC_crop/LCC_FINAL_01485.png'}
      ],
      images_2:[
        {url:'./assets/images/01_Lé com Cré/02_LCC_crop/LCC_FINAL_01384.png'},
        {url:'./assets/images/01_Lé com Cré/02_LCC_crop/LCC_FINAL_01386.png'},
        {url:'./assets/images/01_Lé com Cré/02_LCC_crop/LCC_FINAL_01388.png'},
        {url:'./assets/images/01_Lé com Cré/02_LCC_crop/LCC_FINAL_01390.png'},
        {url:'./assets/images/01_Lé com Cré/02_LCC_crop/LCC_FINAL_01392.png'},
        {url:'./assets/images/01_Lé com Cré/02_LCC_crop/LCC_FINAL_01394.png'},
        {url:'./assets/images/01_Lé com Cré/02_LCC_crop/LCC_FINAL_01396.png'},
        {url:'./assets/images/01_Lé com Cré/02_LCC_crop/LCC_FINAL_01398.png'},
        {url:'./assets/images/01_Lé com Cré/02_LCC_crop/LCC_FINAL_01402.png'},
        {url:'./assets/images/01_Lé com Cré/02_LCC_crop/LCC_FINAL_01404.png'},
        {url:'./assets/images/01_Lé com Cré/02_LCC_crop/LCC_FINAL_01406.png'},
        {url:'./assets/images/01_Lé com Cré/02_LCC_crop/LCC_FINAL_01408.png'}
      ],
      images_3:[
        {url:'./assets/images/01_Lé com Cré/03_LCC_crop/LCC_FINAL_04414.png'},
        {url:'./assets/images/01_Lé com Cré/03_LCC_crop/LCC_FINAL_04416.png'},
        {url:'./assets/images/01_Lé com Cré/03_LCC_crop/LCC_FINAL_04418.png'},
        {url:'./assets/images/01_Lé com Cré/03_LCC_crop/LCC_FINAL_04420.png'},
        {url:'./assets/images/01_Lé com Cré/03_LCC_crop/LCC_FINAL_04422.png'},
        {url:'./assets/images/01_Lé com Cré/03_LCC_crop/LCC_FINAL_04424.png'},
        {url:'./assets/images/01_Lé com Cré/03_LCC_crop/LCC_FINAL_04425.png'},
        {url:'./assets/images/01_Lé com Cré/03_LCC_crop/LCC_FINAL_04427.png'},
        {url:'./assets/images/01_Lé com Cré/03_LCC_crop/LCC_FINAL_04428.png'},
        {url:'./assets/images/01_Lé com Cré/03_LCC_crop/LCC_FINAL_04430.png'},
        {url:'./assets/images/01_Lé com Cré/03_LCC_crop/LCC_FINAL_04431.png'},
        {url:'./assets/images/01_Lé com Cré/03_LCC_crop/LCC_FINAL_04433.png'}
      ],
      title:'LCC_TITLE',
      sub:'LCC_SUBTITLE',
      autor:'LCC_AUTOR',
      texto_1:'LCC_TEXTO_1',
      texto_2:'LCC_TEXTO_2',
      equipe:'LCC_EQUIPE_TITLE',
      equipe_txts:['LCC_EQUIPE_LINE_1','LCC_EQUIPE_LINE_2','LCC_EQUIPE_LINE_3','LCC_EQUIPE_LINE_4','LCC_EQUIPE_LINE_5','LCC_EQUIPE_LINE_6','LCC_EQUIPE_LINE_7','LCC_EQUIPE_LINE_8','LCC_EQUIPE_LINE_9','LCC_EQUIPE_LINE_10','LCC_EQUIPE_LINE_11'],
      elenco:'LCC_ELENCO',
      elenco_txts:['LCC_ELENCO_LINE_1','LCC_ELENCO_LINE_2','LCC_ELENCO_LINE_3','LCC_ELENCO_LINE_4','LCC_ELENCO_LINE_5','LCC_ELENCO_LINE_6','LCC_ELENCO_LINE_7'],
      premio:'LCC_PREMIACOES',
      premiacoes_txts:['LCC_PREMIACOES_LINE_1','LCC_PREMIACOES_LINE_2','LCC_PREMIACOES_LINE_3','LCC_PREMIACOES_LINE_4', 'LCC_PREMIACOES_LINE_5', 'LCC_PREMIACOES_LINE_6'],
      selecao_oficial:'LCC_SELECAO',
      selecao_oficial_txt:['LCC_SELECAO_LINE_1',
      'LCC_SELECAO_LINE_2',
      'LCC_SELECAO_LINE_3',
      'LCC_SELECAO_LINE_4',
      'LCC_SELECAO_LINE_5',
      'LCC_SELECAO_LINE_6',
      'LCC_SELECAO_LINE_7',
      'LCC_SELECAO_LINE_8',
      'LCC_SELECAO_LINE_9',
      'LCC_SELECAO_LINE_10',
      'LCC_SELECAO_LINE_11',
      'LCC_SELECAO_LINE_12',
      'LCC_SELECAO_LINE_13',
      'LCC_SELECAO_LINE_14',
      'LCC_SELECAO_LINE_15',
      'LCC_SELECAO_LINE_16',
      'LCC_SELECAO_LINE_17',
      'LCC_SELECAO_LINE_18',
      'LCC_SELECAO_LINE_19',
      'LCC_SELECAO_LINE_20',
      'LCC_SELECAO_LINE_21',
      'LCC_SELECAO_LINE_22',
      'LCC_SELECAO_LINE_23',
      'LCC_SELECAO_LINE_24',
      'LCC_SELECAO_LINE_25',
      'LCC_SELECAO_LINE_26',
      'LCC_SELECAO_LINE_27',
      'LCC_SELECAO_LINE_28',
      'LCC_SELECAO_LINE_29',
      'LCC_SELECAO_LINE_30',
      'LCC_SELECAO_LINE_31',
      'LCC_SELECAO_LINE_32']
    },
    {
      id:'Cefalopodes',
      images_1:[
        {url:'./assets/images/02_Cefalópodes/CEF_01_crop/CEF_AnimaticV2 (0-00-55-17).png'},
        {url:'./assets/images/02_Cefalópodes/CEF_01_crop/CEF_AnimaticV2 (0-00-56-05).png'},
        {url:'./assets/images/02_Cefalópodes/CEF_01_crop/CEF_AnimaticV2 (0-00-56-20).png'},
        {url:'./assets/images/02_Cefalópodes/CEF_01_crop/CEF_AnimaticV2 (0-00-57-16).png'},
        {url:'./assets/images/02_Cefalópodes/CEF_01_crop/CEF_AnimaticV2 (0-00-58-07).png'},
        {url:'./assets/images/02_Cefalópodes/CEF_01_crop/CEF_AnimaticV2 (0-00-59-01).png'},
        {url:'./assets/images/02_Cefalópodes/CEF_01_crop/CEF_AnimaticV2 (0-00-59-02).png'},
        {url:'./assets/images/02_Cefalópodes/CEF_01_crop/CEF_AnimaticV2 (0-00-59-14).png'},
        {url:'./assets/images/02_Cefalópodes/CEF_01_crop/CEF_AnimaticV2 (0-00-59-21).png'},
        {url:'./assets/images/02_Cefalópodes/CEF_01_crop/CEF_AnimaticV2 (0-01-00-06).png'},
        {url:'./assets/images/02_Cefalópodes/CEF_01_crop/CEF_AnimaticV2 (0-01-00-15).png'},
        {url:'./assets/images/02_Cefalópodes/CEF_01_crop/CEF_AnimaticV2 (0-01-00-23).png'}
      ],
      images_2:[
        {url:'./assets/images/02_Cefalópodes/CEF_02_crop/CEF_AnimaticV3_05234.png'},
        {url:'./assets/images/02_Cefalópodes/CEF_02_crop/CEF_AnimaticV3_05242.png'},
        {url:'./assets/images/02_Cefalópodes/CEF_02_crop/CEF_AnimaticV3_05245.png'},
        {url:'./assets/images/02_Cefalópodes/CEF_02_crop/CEF_AnimaticV3_05248.png'},
        {url:'./assets/images/02_Cefalópodes/CEF_02_crop/CEF_AnimaticV3_05251.png'},
        {url:'./assets/images/02_Cefalópodes/CEF_02_crop/CEF_AnimaticV3_05254.png'},
        {url:'./assets/images/02_Cefalópodes/CEF_02_crop/CEF_AnimaticV3_05257.png'},
        {url:'./assets/images/02_Cefalópodes/CEF_02_crop/CEF_AnimaticV3_05260.png'},
        {url:'./assets/images/02_Cefalópodes/CEF_02_crop/CEF_AnimaticV3_05263.png'},
        {url:'./assets/images/02_Cefalópodes/CEF_02_crop/CEF_AnimaticV3_05283.png'},
        {url:'./assets/images/02_Cefalópodes/CEF_02_crop/CEF_AnimaticV3_05291.png'},
        {url:'./assets/images/02_Cefalópodes/CEF_02_crop/CEF_AnimaticV3_05300.png'}
      ],
      images_3:[
        {url:'./assets/images/02_Cefalópodes/CEF_03_crop/CEF_AnimaticV3_17641.png'},
        {url:'./assets/images/02_Cefalópodes/CEF_03_crop/CEF_AnimaticV3_17642.png'},
        {url:'./assets/images/02_Cefalópodes/CEF_03_crop/CEF_AnimaticV3_17643.png'},
        {url:'./assets/images/02_Cefalópodes/CEF_03_crop/CEF_AnimaticV3_17654.png'},
        {url:'./assets/images/02_Cefalópodes/CEF_03_crop/CEF_AnimaticV3_17664.png'},
        {url:'./assets/images/02_Cefalópodes/CEF_03_crop/CEF_AnimaticV3_17672.png'},
        {url:'./assets/images/02_Cefalópodes/CEF_03_crop/CEF_AnimaticV3_17685.png'},
        {url:'./assets/images/02_Cefalópodes/CEF_03_crop/CEF_AnimaticV3_17698.png'},
        {url:'./assets/images/02_Cefalópodes/CEF_03_crop/CEF_AnimaticV3_17703.png'},
        {url:'./assets/images/02_Cefalópodes/CEF_03_crop/CEF_AnimaticV3_17710.png'},
        {url:'./assets/images/02_Cefalópodes/CEF_03_crop/CEF_AnimaticV3_17713.png'},
        {url:'./assets/images/02_Cefalópodes/CEF_03_crop/CEF_AnimaticV3_17714.png'}
      ],
      title:'CEF_TITLE',
      sub:'CEF_SUBTITLE',
      autor:'CEF_AUTOR',
      texto_1:'CEF_TEXTO_1',
      texto_2:'CEF_TEXTO_2',
      equipe:'CEF_EQUIPE',
      equipe_txts:['CEF_EQUIPE_LINE_1','CEF_EQUIPE_LINE_2','CEF_EQUIPE_LINE_3','CEF_EQUIPE_LINE_4','CEF_EQUIPE_LINE_5','CEF_EQUIPE_LINE_6','CEF_EQUIPE_LINE_7','CEF_EQUIPE_LINE_8','CEF_EQUIPE_LINE_9','CEF_EQUIPE_LINE_10','CEF_EQUIPE_LINE_11','CEF_EQUIPE_LINE_12'],
      elenco_txts:['CEF_ELENCO_LINE_1','CEF_ELENCO_LINE_2','CEF_ELENCO_LINE_3'],
      premiacoes_txts:['CEF_PREMIACOES_LINE_1'],

    },
    {
      id:'CambioDesligo',
      images_1:[
        {url:'./assets/images/03_Câmbio, Desligo/CAM_01.png'},
      ],
      images_2:[
        {url:'./assets/images/03_Câmbio, Desligo/CAM_02.png'},
      ],
      images_3:[
        {url:'./assets/images/03_Câmbio, Desligo/CAM_03.png'},
      ],
      title:'CAD_TITLE',
      sub:'CAD_SUBTITLE',
      autor:'CAD_AUTOR',
      texto_1:'CAD_TEXTO_1',
      texto_2:'CAD_TEXTO_2',
      equipe:'CAD_EQUIPE',
      equipe_txts:['CAD_EQUIPE_LINE_1'],
      elenco_txts:['CAD_ELENCO_LINE_1'],
      selecao_oficial_txt:['CAD_SELECAO_LINE_1','CAD_SELECAO_LINE_2','CAD_SELECAO_LINE_3']
    },
    {
      id:'Servicos',
      images_1:[
        {url:'./assets/images/04_Serviços/01/BlocoServicos_FRAMES_V0200.png'},
        {url:'./assets/images/04_Serviços/01/BlocoServicos_FRAMES_V0201.png'},
        {url:'./assets/images/04_Serviços/01/BlocoServicos_FRAMES_V0202.png'},
        {url:'./assets/images/04_Serviços/01/BlocoServicos_FRAMES_V0203.png'},
        {url:'./assets/images/04_Serviços/01/BlocoServicos_FRAMES_V0204.png'},
        {url:'./assets/images/04_Serviços/01/BlocoServicos_FRAMES_V0205.png'},
        {url:'./assets/images/04_Serviços/01/BlocoServicos_FRAMES_V0206.png'},
        {url:'./assets/images/04_Serviços/01/BlocoServicos_FRAMES_V0207.png'},
        {url:'./assets/images/04_Serviços/01/BlocoServicos_FRAMES_V0208.png'},
        {url:'./assets/images/04_Serviços/01/BlocoServicos_FRAMES_V0209.png'},
        {url:'./assets/images/04_Serviços/01/BlocoServicos_FRAMES_V0210.png'},
        {url:'./assets/images/04_Serviços/01/BlocoServicos_FRAMES_V0211.png'},
        {url:'./assets/images/04_Serviços/01/BlocoServicos_FRAMES_V0212.png'}
      ],
      images_2:[
        {url:'./assets/images/04_Serviços/02/BlocoServicos_FRAMES_V0213.png'},
        {url:'./assets/images/04_Serviços/02/BlocoServicos_FRAMES_V0214.png'},
        {url:'./assets/images/04_Serviços/02/BlocoServicos_FRAMES_V0215.png'},
        {url:'./assets/images/04_Serviços/02/BlocoServicos_FRAMES_V0216.png'},
        {url:'./assets/images/04_Serviços/02/BlocoServicos_FRAMES_V0217.png'},
        {url:'./assets/images/04_Serviços/02/BlocoServicos_FRAMES_V0218.png'},
        {url:'./assets/images/04_Serviços/02/BlocoServicos_FRAMES_V0219.png'},
        {url:'./assets/images/04_Serviços/02/BlocoServicos_FRAMES_V0220.png'},
        {url:'./assets/images/04_Serviços/02/BlocoServicos_FRAMES_V0221.png'},
        {url:'./assets/images/04_Serviços/02/BlocoServicos_FRAMES_V0222.png'},
        {url:'./assets/images/04_Serviços/02/BlocoServicos_FRAMES_V0223.png'},
        {url:'./assets/images/04_Serviços/02/BlocoServicos_FRAMES_V0224.png'},
        {url:'./assets/images/04_Serviços/02/BlocoServicos_FRAMES_V0225.png'}
      ],
      images_3:[
        {url:'./assets/images/04_Serviços/03/BlocoServicos_FRAMES_V0226.png'},
        {url:'./assets/images/04_Serviços/03/BlocoServicos_FRAMES_V0227.png'},
        {url:'./assets/images/04_Serviços/03/BlocoServicos_FRAMES_V0228.png'},
        {url:'./assets/images/04_Serviços/03/BlocoServicos_FRAMES_V0229.png'},
        {url:'./assets/images/04_Serviços/03/BlocoServicos_FRAMES_V0230.png'},
        {url:'./assets/images/04_Serviços/03/BlocoServicos_FRAMES_V0231.png'},
        {url:'./assets/images/04_Serviços/03/BlocoServicos_FRAMES_V0232.png'},
        {url:'./assets/images/04_Serviços/03/BlocoServicos_FRAMES_V0233.png'},
        {url:'./assets/images/04_Serviços/03/BlocoServicos_FRAMES_V0234.png'},
        {url:'./assets/images/04_Serviços/03/BlocoServicos_FRAMES_V0235.png'},
        {url:'./assets/images/04_Serviços/03/BlocoServicos_FRAMES_V0236.png'},
        {url:'./assets/images/04_Serviços/03/BlocoServicos_FRAMES_V0237.png'},
        {url:'./assets/images/04_Serviços/03/BlocoServicos_FRAMES_V0238.png'}
      ],
      title:'SER_TITLE',
      sub:'SER_SUBTITLE',
      autor:'SER_AUTOR',
      texto_1:'SER_TEXTO_1',
      texto_2:'SER_TEXTO_2',
      equipe:'SER_EQUIPE'
    }
  ];
  constructor() { }
}
